services:
  vision_classification:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images:rw
      - ./models:/root/.cache/huggingface/hub:rw
      - ./mediapipe_models:/app/mediapipe_models:rw
      - ./models:/app/models:rw
    env_file:
      - .env
    restart: unless-stopped
